### ISSUE TITLE
Add List Sample Apps

### ISSUE THREAD

**Issue by armiaabdurohman** [Carlos487/awesome-wpf#12]
It would be great to have a list sample wpf application

**Comment by Carlos487** [comment]
Thanks for your suggestion I will search for good example apps. Do you have any app you would like to suggest?

**Comment by armiaabdurohman** [comment]
Thank you for answering. 
Maybe [The World's Simplest C# WPF MVVM Example](https://github.com/MarkWithall/worlds-simplest-csharp-wpf-mvvm-example) and [SimpleTrader](https://github.com/SingletonSean/SimpleTrader) will be a good example

**Comment by Carlos487** [comment]
I just added the apps suggested, I will keep looking for more examples. Thanks for the suggestion.
