### ISSUE TITLE
Add LightningChart and SciChart 

### ISSUE THREAD

**Issue by cordasfilip** [Carlos487/awesome-wpf#14]
Since you have commercial libraries you should add
[SciCharts](https://www.scichart.com/) and [LightningCharts](https://www.arction.com/)
They are really similar, and look really high-quality
NOTE: I am in no way affiliated with any of the two companies, I just hope the offer some sort of community license.

**Comment by Carlos487** [comment]
Thanks for the suggestion. Changes were added.
