### ISSUE TITLE
The project is missing - The World's Simplest C# WPF MVVM Example

### ISSUE THREAD

**Issue by it19862** [Carlos487/awesome-wpf#18]
The project is missing - The World's Simplest C# WPF MVVM Example.
Project [The World's Simplest C# WPF MVVM Example](https://github.com/MarkWithall/worlds-simplest-csharp-wpf-mvvm-example) - A simple MVVM example using WPF and C# 9.

The repository is empty.

**Comment by kaiiiiiiiii** [comment]
No it's not, just read the readme carefully ... :)
